# Generated by Django 4.2.4 on 2023-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_rename_gamewords_gameword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_of_room", models.CharField(max_length=100)),
                ("number_of_room", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "number_of_room"],
            },
        ),
    ]
