# Generated by Django 4.2.4 on 2023-08-08 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameWords",
            new_name="GameWord",
        ),
    ]
